name: Deploy to Staging

on:
  push:
    branches: [ develop ]

jobs:
  deploy-staging:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1
        
    - name: Deploy to staging S3 bucket
      run: |
        aws s3 sync website/ s3://${{ secrets.S3_BUCKET_NAME }}-staging \
          --delete \
          --exact-timestamps
        
    - name: Staging deployment complete
      run: |
        echo "🚧 Staging deployment completed!"
        echo "🔍 Review changes at staging URL before promoting to production"